// Mocks generated by Mockito 5.4.4 from annotations
// in com_nicodevelop_xmagicmovie/test/services/upload_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i4;

import 'package:com_nicodevelop_xmagicmovie/models/crop_model.dart' as _i9;
import 'package:com_nicodevelop_xmagicmovie/models/size_model.dart' as _i3;
import 'package:com_nicodevelop_xmagicmovie/models/video_data_model.dart'
    as _i8;
import 'package:com_nicodevelop_xmagicmovie/services/file_manager.dart' as _i2;
import 'package:com_nicodevelop_xmagicmovie/services/video_manager.dart' as _i5;
import 'package:cross_file/cross_file.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFileManager_0 extends _i1.SmartFake implements _i2.FileManager {
  _FakeFileManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSizeModel_1 extends _i1.SmartFake implements _i3.SizeModel {
  _FakeSizeModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectory_2 extends _i1.SmartFake implements _i4.Directory {
  _FakeDirectory_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VideoManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoManager extends _i1.Mock implements _i5.VideoManager {
  MockVideoManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FileManager get fileManager => (super.noSuchMethod(
        Invocation.getter(#fileManager),
        returnValue: _FakeFileManager_0(
          this,
          Invocation.getter(#fileManager),
        ),
      ) as _i2.FileManager);

  @override
  _i6.Future<_i3.SizeModel> getVideoSize(_i7.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoSize,
          [file],
        ),
        returnValue: _i6.Future<_i3.SizeModel>.value(_FakeSizeModel_1(
          this,
          Invocation.method(
            #getVideoSize,
            [file],
          ),
        )),
      ) as _i6.Future<_i3.SizeModel>);

  @override
  _i6.Future<void> cropVideo(
    _i8.VideoDataModel? file,
    _i3.SizeModel? videoSize,
    _i9.CropModel? crop,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cropVideo,
          [
            file,
            videoSize,
            crop,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [FileManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileManager extends _i1.Mock implements _i2.FileManager {
  MockFileManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Directory> getWorkingDirectory() => (super.noSuchMethod(
        Invocation.method(
          #getWorkingDirectory,
          [],
        ),
        returnValue: _i6.Future<_i4.Directory>.value(_FakeDirectory_2(
          this,
          Invocation.method(
            #getWorkingDirectory,
            [],
          ),
        )),
      ) as _i6.Future<_i4.Directory>);

  @override
  String getFileName(_i7.XFile? file) => (super.noSuchMethod(
        Invocation.method(
          #getFileName,
          [file],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getFileName,
            [file],
          ),
        ),
      ) as String);

  @override
  _i6.Future<Map<String, String>> generateUniqueFileName(_i7.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateUniqueFileName,
          [file],
        ),
        returnValue: _i6.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<String> getFilePath(
    String? projectId,
    String? fileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilePath,
          [
            projectId,
            fileName,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getFilePath,
            [
              projectId,
              fileName,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> saveJsonFile(
    String? path,
    String? fileName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJsonFile,
          [
            path,
            fileName,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> readJsonFile(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #readJsonFile,
          [path],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> deleteDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #deleteDirectory,
          [path],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
