// Mocks generated by Mockito 5.4.4 from annotations
// in com_nicodevelop_xmagicmovie/test/components/button_transcription/transcription_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:com_nicodevelop_xmagicmovie/gateway/openai_gateway.dart' as _i2;
import 'package:com_nicodevelop_xmagicmovie/models/config_model.dart' as _i9;
import 'package:com_nicodevelop_xmagicmovie/models/transcription_model.dart'
    as _i4;
import 'package:com_nicodevelop_xmagicmovie/services/config_service.dart'
    as _i8;
import 'package:com_nicodevelop_xmagicmovie/services/file_manager.dart' as _i5;
import 'package:com_nicodevelop_xmagicmovie/services/transcription_service.dart'
    as _i6;
import 'package:com_nicodevelop_xmagicmovie/services/video_manager.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOpenaiGateway_0 extends _i1.SmartFake implements _i2.OpenaiGateway {
  _FakeOpenaiGateway_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoManager_1 extends _i1.SmartFake implements _i3.VideoManager {
  _FakeVideoManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTranscriptionModel_2 extends _i1.SmartFake
    implements _i4.TranscriptionModel {
  _FakeTranscriptionModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileManager_3 extends _i1.SmartFake implements _i5.FileManager {
  _FakeFileManager_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TranscriptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTranscriptionService extends _i1.Mock
    implements _i6.TranscriptionService {
  MockTranscriptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OpenaiGateway get openaiGateway => (super.noSuchMethod(
        Invocation.getter(#openaiGateway),
        returnValue: _FakeOpenaiGateway_0(
          this,
          Invocation.getter(#openaiGateway),
        ),
      ) as _i2.OpenaiGateway);

  @override
  _i3.VideoManager get videoManager => (super.noSuchMethod(
        Invocation.getter(#videoManager),
        returnValue: _FakeVideoManager_1(
          this,
          Invocation.getter(#videoManager),
        ),
      ) as _i3.VideoManager);

  @override
  _i7.Future<_i4.TranscriptionModel> transcribeAudioToText(
    String? projectId,
    String? sourceFileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeAudioToText,
          [
            projectId,
            sourceFileName,
          ],
        ),
        returnValue:
            _i7.Future<_i4.TranscriptionModel>.value(_FakeTranscriptionModel_2(
          this,
          Invocation.method(
            #transcribeAudioToText,
            [
              projectId,
              sourceFileName,
            ],
          ),
        )),
      ) as _i7.Future<_i4.TranscriptionModel>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i8.ConfigService {
  MockConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FileManager get fileManager => (super.noSuchMethod(
        Invocation.getter(#fileManager),
        returnValue: _FakeFileManager_3(
          this,
          Invocation.getter(#fileManager),
        ),
      ) as _i5.FileManager);

  @override
  _i7.Future<List<_i9.ConfigModel>> loadConfigs() => (super.noSuchMethod(
        Invocation.method(
          #loadConfigs,
          [],
        ),
        returnValue:
            _i7.Future<List<_i9.ConfigModel>>.value(<_i9.ConfigModel>[]),
      ) as _i7.Future<List<_i9.ConfigModel>>);

  @override
  _i7.Future<void> saveConfig(_i9.ConfigModel? config) => (super.noSuchMethod(
        Invocation.method(
          #saveConfig,
          [config],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
