// Mocks generated by Mockito 5.4.4 from annotations
// in com_nicodevelop_xmagicmovie/test/tools/run_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:com_nicodevelop_xmagicmovie/models/crop_model.dart' as _i8;
import 'package:com_nicodevelop_xmagicmovie/models/size_model.dart' as _i3;
import 'package:com_nicodevelop_xmagicmovie/models/video_data_model.dart'
    as _i4;
import 'package:com_nicodevelop_xmagicmovie/services/file_manager.dart' as _i2;
import 'package:com_nicodevelop_xmagicmovie/services/video_manager.dart' as _i5;
import 'package:cross_file/cross_file.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFileManager_0 extends _i1.SmartFake implements _i2.FileManager {
  _FakeFileManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSizeModel_1 extends _i1.SmartFake implements _i3.SizeModel {
  _FakeSizeModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoDataModel_2 extends _i1.SmartFake
    implements _i4.VideoDataModel {
  _FakeVideoDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VideoManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoManager extends _i1.Mock implements _i5.VideoManager {
  MockVideoManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FileManager get fileManager => (super.noSuchMethod(
        Invocation.getter(#fileManager),
        returnValue: _FakeFileManager_0(
          this,
          Invocation.getter(#fileManager),
        ),
      ) as _i2.FileManager);

  @override
  _i6.Future<_i3.SizeModel> getVideoSize(_i7.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoSize,
          [file],
        ),
        returnValue: _i6.Future<_i3.SizeModel>.value(_FakeSizeModel_1(
          this,
          Invocation.method(
            #getVideoSize,
            [file],
          ),
        )),
      ) as _i6.Future<_i3.SizeModel>);

  @override
  _i6.Future<String?> cropVideo(
    _i4.VideoDataModel? file,
    _i3.SizeModel? videoSize,
    _i8.CropModel? crop,
    void Function(int)? onProgress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cropVideo,
          [
            file,
            videoSize,
            crop,
            onProgress,
          ],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i4.VideoDataModel> createVideoDataModel(
    String? projectId,
    String? sourceFileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVideoDataModel,
          [
            projectId,
            sourceFileName,
          ],
        ),
        returnValue: _i6.Future<_i4.VideoDataModel>.value(_FakeVideoDataModel_2(
          this,
          Invocation.method(
            #createVideoDataModel,
            [
              projectId,
              sourceFileName,
            ],
          ),
        )),
      ) as _i6.Future<_i4.VideoDataModel>);

  @override
  _i6.Future<_i4.VideoDataModel> processFile(_i7.XFile? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #processFile,
          [file],
        ),
        returnValue: _i6.Future<_i4.VideoDataModel>.value(_FakeVideoDataModel_2(
          this,
          Invocation.method(
            #processFile,
            [file],
          ),
        )),
      ) as _i6.Future<_i4.VideoDataModel>);
}
